export type PhoneCountryCodeOption = {
  iso: string
  country: string
  dialCode: string
  minDigits: number
  maxDigits: number
}

const defaultDigits = (dialCode: string) => Math.max(4, 15 - dialCode.replace(/\D/g, '').length)

function code(iso: string, country: string, dialCode: string, digits?: number): PhoneCountryCodeOption {
  const maxDigits = digits ?? defaultDigits(dialCode)
  return { iso, country, dialCode, minDigits: digits ?? 4, maxDigits }
}

export const DEFAULT_PHONE_COUNTRY_ISO = 'IN'

export const PHONE_COUNTRY_CODES: PhoneCountryCodeOption[] = [
  code('AF', 'Afghanistan', '+93', 9),
  code('AX', 'Aland Islands', '+358'),
  code('AL', 'Albania', '+355'),
  code('DZ', 'Algeria', '+213', 9),
  code('AS', 'American Samoa', '+1684', 7),
  code('AD', 'Andorra', '+376'),
  code('AO', 'Angola', '+244', 9),
  code('AI', 'Anguilla', '+1264', 7),
  code('AG', 'Antigua and Barbuda', '+1268', 7),
  code('AR', 'Argentina', '+54', 10),
  code('AM', 'Armenia', '+374', 8),
  code('AW', 'Aruba', '+297', 7),
  code('AU', 'Australia', '+61', 9),
  code('AT', 'Austria', '+43'),
  code('AZ', 'Azerbaijan', '+994', 9),
  code('BS', 'Bahamas', '+1242', 7),
  code('BH', 'Bahrain', '+973', 8),
  code('BD', 'Bangladesh', '+880', 10),
  code('BB', 'Barbados', '+1246', 7),
  code('BY', 'Belarus', '+375', 9),
  code('BE', 'Belgium', '+32', 9),
  code('BZ', 'Belize', '+501', 7),
  code('BJ', 'Benin', '+229', 8),
  code('BM', 'Bermuda', '+1441', 7),
  code('BT', 'Bhutan', '+975', 8),
  code('BO', 'Bolivia', '+591', 8),
  code('BQ', 'Bonaire, Sint Eustatius and Saba', '+599'),
  code('BA', 'Bosnia and Herzegovina', '+387', 8),
  code('BW', 'Botswana', '+267'),
  code('BR', 'Brazil', '+55', 11),
  code('IO', 'British Indian Ocean Territory', '+246', 7),
  code('VG', 'British Virgin Islands', '+1284', 7),
  code('BN', 'Brunei', '+673', 7),
  code('BG', 'Bulgaria', '+359', 9),
  code('BF', 'Burkina Faso', '+226', 8),
  code('BI', 'Burundi', '+257', 8),
  code('KH', 'Cambodia', '+855'),
  code('CM', 'Cameroon', '+237', 9),
  code('CA', 'Canada', '+1', 10),
  code('CV', 'Cape Verde', '+238', 7),
  code('KY', 'Cayman Islands', '+1345', 7),
  code('CF', 'Central African Republic', '+236', 8),
  code('TD', 'Chad', '+235', 8),
  code('CL', 'Chile', '+56', 9),
  code('CN', 'China', '+86', 11),
  code('CX', 'Christmas Island', '+61', 9),
  code('CC', 'Cocos Islands', '+61', 9),
  code('CO', 'Colombia', '+57', 10),
  code('KM', 'Comoros', '+269', 7),
  code('CG', 'Congo', '+242', 9),
  code('CD', 'Congo Democratic Republic', '+243', 9),
  code('CK', 'Cook Islands', '+682', 5),
  code('CR', 'Costa Rica', '+506', 8),
  code('CI', 'Cote dIvoire', '+225', 10),
  code('HR', 'Croatia', '+385', 9),
  code('CU', 'Cuba', '+53', 8),
  code('CW', 'Curacao', '+599'),
  code('CY', 'Cyprus', '+357', 8),
  code('CZ', 'Czech Republic', '+420', 9),
  code('DK', 'Denmark', '+45', 8),
  code('DJ', 'Djibouti', '+253', 8),
  code('DM', 'Dominica', '+1767', 7),
  code('DO', 'Dominican Republic', '+1809', 7),
  code('EC', 'Ecuador', '+593', 9),
  code('EG', 'Egypt', '+20', 10),
  code('SV', 'El Salvador', '+503', 8),
  code('GQ', 'Equatorial Guinea', '+240', 9),
  code('ER', 'Eritrea', '+291', 7),
  code('EE', 'Estonia', '+372'),
  code('SZ', 'Eswatini', '+268', 8),
  code('ET', 'Ethiopia', '+251', 9),
  code('FK', 'Falkland Islands', '+500', 5),
  code('FO', 'Faroe Islands', '+298', 6),
  code('FJ', 'Fiji', '+679', 7),
  code('FI', 'Finland', '+358'),
  code('FR', 'France', '+33', 9),
  code('GF', 'French Guiana', '+594', 9),
  code('PF', 'French Polynesia', '+689'),
  code('GA', 'Gabon', '+241', 8),
  code('GM', 'Gambia', '+220', 7),
  code('GE', 'Georgia', '+995', 9),
  code('DE', 'Germany', '+49'),
  code('GH', 'Ghana', '+233', 9),
  code('GI', 'Gibraltar', '+350', 8),
  code('GR', 'Greece', '+30', 10),
  code('GL', 'Greenland', '+299', 6),
  code('GD', 'Grenada', '+1473', 7),
  code('GP', 'Guadeloupe', '+590', 9),
  code('GU', 'Guam', '+1671', 7),
  code('GT', 'Guatemala', '+502', 8),
  code('GG', 'Guernsey', '+44', 10),
  code('GN', 'Guinea', '+224', 9),
  code('GW', 'Guinea-Bissau', '+245', 7),
  code('GY', 'Guyana', '+592', 7),
  code('HT', 'Haiti', '+509', 8),
  code('HN', 'Honduras', '+504', 8),
  code('HK', 'Hong Kong', '+852', 8),
  code('HU', 'Hungary', '+36', 9),
  code('IS', 'Iceland', '+354', 7),
  code('IN', 'India', '+91', 10),
  code('ID', 'Indonesia', '+62'),
  code('IR', 'Iran', '+98', 10),
  code('IQ', 'Iraq', '+964', 10),
  code('IE', 'Ireland', '+353', 9),
  code('IM', 'Isle of Man', '+44', 10),
  code('IL', 'Israel', '+972', 9),
  code('IT', 'Italy', '+39'),
  code('JM', 'Jamaica', '+1876', 7),
  code('JP', 'Japan', '+81', 10),
  code('JE', 'Jersey', '+44', 10),
  code('JO', 'Jordan', '+962', 9),
  code('KZ', 'Kazakhstan', '+7', 10),
  code('KE', 'Kenya', '+254', 9),
  code('KI', 'Kiribati', '+686'),
  code('XK', 'Kosovo', '+383'),
  code('KW', 'Kuwait', '+965', 8),
  code('KG', 'Kyrgyzstan', '+996', 9),
  code('LA', 'Laos', '+856'),
  code('LV', 'Latvia', '+371', 8),
  code('LB', 'Lebanon', '+961', 8),
  code('LS', 'Lesotho', '+266', 8),
  code('LR', 'Liberia', '+231'),
  code('LY', 'Libya', '+218', 9),
  code('LI', 'Liechtenstein', '+423', 7),
  code('LT', 'Lithuania', '+370', 8),
  code('LU', 'Luxembourg', '+352'),
  code('MO', 'Macao', '+853', 8),
  code('MG', 'Madagascar', '+261', 9),
  code('MW', 'Malawi', '+265'),
  code('MY', 'Malaysia', '+60'),
  code('MV', 'Maldives', '+960', 7),
  code('ML', 'Mali', '+223', 8),
  code('MT', 'Malta', '+356', 8),
  code('MH', 'Marshall Islands', '+692', 7),
  code('MQ', 'Martinique', '+596', 9),
  code('MR', 'Mauritania', '+222', 8),
  code('MU', 'Mauritius', '+230', 8),
  code('YT', 'Mayotte', '+262', 9),
  code('MX', 'Mexico', '+52', 10),
  code('FM', 'Micronesia', '+691', 7),
  code('MD', 'Moldova', '+373', 8),
  code('MC', 'Monaco', '+377'),
  code('MN', 'Mongolia', '+976', 8),
  code('ME', 'Montenegro', '+382'),
  code('MS', 'Montserrat', '+1664', 7),
  code('MA', 'Morocco', '+212', 9),
  code('MZ', 'Mozambique', '+258', 9),
  code('MM', 'Myanmar', '+95'),
  code('NA', 'Namibia', '+264'),
  code('NR', 'Nauru', '+674', 7),
  code('NP', 'Nepal', '+977', 10),
  code('NL', 'Netherlands', '+31', 9),
  code('NC', 'New Caledonia', '+687', 6),
  code('NZ', 'New Zealand', '+64'),
  code('NI', 'Nicaragua', '+505', 8),
  code('NE', 'Niger', '+227', 8),
  code('NG', 'Nigeria', '+234', 10),
  code('NU', 'Niue', '+683', 4),
  code('NF', 'Norfolk Island', '+672'),
  code('KP', 'North Korea', '+850'),
  code('MK', 'North Macedonia', '+389', 8),
  code('MP', 'Northern Mariana Islands', '+1670', 7),
  code('NO', 'Norway', '+47', 8),
  code('OM', 'Oman', '+968', 8),
  code('PK', 'Pakistan', '+92', 10),
  code('PW', 'Palau', '+680', 7),
  code('PS', 'Palestine', '+970', 9),
  code('PA', 'Panama', '+507', 8),
  code('PG', 'Papua New Guinea', '+675'),
  code('PY', 'Paraguay', '+595', 9),
  code('PE', 'Peru', '+51', 9),
  code('PH', 'Philippines', '+63', 10),
  code('PL', 'Poland', '+48', 9),
  code('PT', 'Portugal', '+351', 9),
  code('PR', 'Puerto Rico', '+1787', 7),
  code('QA', 'Qatar', '+974', 8),
  code('RE', 'Reunion', '+262', 9),
  code('RO', 'Romania', '+40', 9),
  code('RU', 'Russia', '+7', 10),
  code('RW', 'Rwanda', '+250', 9),
  code('BL', 'Saint Barthelemy', '+590', 9),
  code('SH', 'Saint Helena', '+290'),
  code('KN', 'Saint Kitts and Nevis', '+1869', 7),
  code('LC', 'Saint Lucia', '+1758', 7),
  code('MF', 'Saint Martin', '+590', 9),
  code('PM', 'Saint Pierre and Miquelon', '+508', 6),
  code('VC', 'Saint Vincent and the Grenadines', '+1784', 7),
  code('WS', 'Samoa', '+685', 7),
  code('SM', 'San Marino', '+378'),
  code('ST', 'Sao Tome and Principe', '+239', 7),
  code('SA', 'Saudi Arabia', '+966', 9),
  code('SN', 'Senegal', '+221', 9),
  code('RS', 'Serbia', '+381'),
  code('SC', 'Seychelles', '+248', 7),
  code('SL', 'Sierra Leone', '+232'),
  code('SG', 'Singapore', '+65', 8),
  code('SX', 'Sint Maarten', '+1721', 7),
  code('SK', 'Slovakia', '+421', 9),
  code('SI', 'Slovenia', '+386', 8),
  code('SB', 'Solomon Islands', '+677'),
  code('SO', 'Somalia', '+252'),
  code('ZA', 'South Africa', '+27', 9),
  code('KR', 'South Korea', '+82', 10),
  code('SS', 'South Sudan', '+211', 9),
  code('ES', 'Spain', '+34', 9),
  code('LK', 'Sri Lanka', '+94', 9),
  code('SD', 'Sudan', '+249', 9),
  code('SR', 'Suriname', '+597'),
  code('SJ', 'Svalbard and Jan Mayen', '+47', 8),
  code('SE', 'Sweden', '+46', 9),
  code('CH', 'Switzerland', '+41', 9),
  code('SY', 'Syria', '+963', 9),
  code('TW', 'Taiwan', '+886', 9),
  code('TJ', 'Tajikistan', '+992', 9),
  code('TZ', 'Tanzania', '+255', 9),
  code('TH', 'Thailand', '+66', 9),
  code('TL', 'Timor-Leste', '+670'),
  code('TG', 'Togo', '+228', 8),
  code('TK', 'Tokelau', '+690', 4),
  code('TO', 'Tonga', '+676'),
  code('TT', 'Trinidad and Tobago', '+1868', 7),
  code('TN', 'Tunisia', '+216', 8),
  code('TR', 'Turkey', '+90', 10),
  code('TM', 'Turkmenistan', '+993', 8),
  code('TC', 'Turks and Caicos Islands', '+1649', 7),
  code('TV', 'Tuvalu', '+688', 5),
  code('UG', 'Uganda', '+256', 9),
  code('UA', 'Ukraine', '+380', 9),
  code('AE', 'United Arab Emirates', '+971', 9),
  code('GB', 'United Kingdom', '+44', 10),
  code('US', 'United States', '+1', 10),
  code('UY', 'Uruguay', '+598', 8),
  code('VI', 'US Virgin Islands', '+1340', 7),
  code('UZ', 'Uzbekistan', '+998', 9),
  code('VU', 'Vanuatu', '+678'),
  code('VA', 'Vatican City', '+39'),
  code('VE', 'Venezuela', '+58', 10),
  code('VN', 'Vietnam', '+84', 9),
  code('WF', 'Wallis and Futuna', '+681', 6),
  code('EH', 'Western Sahara', '+212', 9),
  code('YE', 'Yemen', '+967', 9),
  code('ZM', 'Zambia', '+260', 9),
  code('ZW', 'Zimbabwe', '+263', 9),
].sort((a, b) => a.country.localeCompare(b.country))

export function findPhoneCountryCode(iso: string): PhoneCountryCodeOption {
  return PHONE_COUNTRY_CODES.find((option) => option.iso === iso) ?? PHONE_COUNTRY_CODES[0]
}

export function sanitizePhoneDigits(value: string, maxDigits: number): string {
  return value.replace(/\D/g, '').slice(0, maxDigits)
}

export function parseInternationalPhone(phone: string | null | undefined): {
  iso: string
  localNumber: string
} {
  const compact = (phone ?? '').replace(/[\s\-()]/g, '')
  const matched = [...PHONE_COUNTRY_CODES]
    .sort((a, b) => b.dialCode.length - a.dialCode.length)
    .find((option) => compact.startsWith(option.dialCode))

  if (!matched) {
    const fallback = findPhoneCountryCode(DEFAULT_PHONE_COUNTRY_ISO)
    return {
      iso: fallback.iso,
      localNumber: sanitizePhoneDigits(compact, fallback.maxDigits),
    }
  }

  return {
    iso: matched.iso,
    localNumber: sanitizePhoneDigits(compact.slice(matched.dialCode.length), matched.maxDigits),
  }
}
